import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const initialState = {
    modal: false,
    status:'',
    userEdit:{}
};


export const modalSlice = createSlice({
    name: 'modal',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        toggleModal: (state, action) => {
            console.log(action)
            if(state.modal == false) {
                state.status = action.payload.status
                state.userEdit = action.payload.userEdit || ''
                state.modal = true;
            } else {
                state.modal = false
            } 
        },
        

    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {

    },
});

export const { toggleModal } = modalSlice.actions;

export default modalSlice.reducer;
